let S={baseId:null,reactId:null,baseMeta:null,reactMeta:null,prompted:false,saveTimer:null};
const TTL=7*24*60*60*1000,MAX=2,IDX='rsync:index';
function sigForLocal(file){if(!file)return null;return 'file:'+file.name+'|'+file.size+'|'+file.lastModified;}
function normUrl(u){try{const x=new URL(u,window.location.href);return 'url:'+x.href;}catch(e){return null}}
function sigForYT(player){try{if(!player||!player.getVideoData)return null;const id=player.getVideoData().video_id;return id?'yt:'+id:null}catch(e){return null}}
function getNow(){return Date.now()}
function getPairKey(){if(!S.baseId||!S.reactId)return null;return 'rsync:pair:'+S.baseId+'||'+S.reactId}
function readIndex(){try{const s=localStorage.getItem(IDX);return s?JSON.parse(s):[]}catch(e){return []}}
function writeIndex(a){try{localStorage.setItem(IDX,JSON.stringify(a))}catch(e){}
}
function prune(){const now=getNow();let idx=readIndex().filter(x=>now-x.t<=TTL);if(idx.length>MAX){idx=idx.sort((a,b)=>b.t-a.t).slice(0,MAX)}writeIndex(idx);const keys=new Set(idx.map(x=>x.k));for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('rsync:pair:')&&!keys.has(k)){try{localStorage.removeItem(k)}catch(e){}}}}
function readPair(k){try{const s=localStorage.getItem(k);return s?JSON.parse(s):null}catch(e){return null}}
function writePair(k,obj){try{localStorage.setItem(k,JSON.stringify(obj))}catch(e){}
let idx=readIndex().filter(x=>x.k!==k);idx.unshift({k,t:getNow()});writeIndex(idx);prune()}
function updateSource(which,id){if(!id)return;if(which==='base')S.baseId=id;else S.reactId=id;if(bothReady()&&!S.saveTimer&&canUseSync())startAutoSave();maybePrompt()}
function recordLocalFile(videoSelector,file){const id=sigForLocal(file);if(videoSelector==="#videoBaseLocal"){S.baseMeta={type:'file',name:file&&file.name};updateSource('base',id)}else{S.reactMeta={type:'file',name:file&&file.name};updateSource('react',id)}}
function recordNetworkSource(videoSelector,meta){let id=null;let m=null;if(meta&&meta.type==='yt'&&meta.id){id='yt:'+meta.id;m={type:'yt',id:meta.id}}else if(meta&&meta.url){id=normUrl(meta.url);m={type:'url',url:meta.url}}if(videoSelector==="#videoBaseLocal"){S.baseMeta=m;updateSource('base',id)}else{S.reactMeta=m;updateSource('react',id)}}
function bothReady(){return !!(S.baseId&&S.reactId)}
function canUseSync(){return typeof window.getBaseCurrentTime==='function'&&typeof window.setDelay==='function'&&typeof window.syncSeek==='function'}
function getPos(){try{const c=document.getElementById('videoReactContainer');if(!c)return null;return {l:c.offsetLeft||0,t:c.offsetTop||0,w:c.offsetWidth||0,h:c.offsetHeight||0}}catch(e){return null}}
function saveNow(){try{if(!bothReady()||!canUseSync())return;const k=getPairKey();if(!k)return;const delay=typeof window.videoReactDelay==='number'?window.videoReactDelay:0;let baseTime=0;try{baseTime=window.getBaseCurrentTime()?window.getBaseCurrentTime():0}catch(e){}
let bv=null,rv=null;try{bv=parseFloat($('#baseVolumeSlider').val())}catch(e){}try{rv=parseFloat($('#reactVolumeSlider').val())}catch(e){}
const obj={baseId:S.baseId,reactId:S.reactId,baseMeta:S.baseMeta,reactMeta:S.reactMeta,delay:delay,baseTime:baseTime,pos:getPos(),baseVol:isFinite(bv)?bv:null,reactVol:isFinite(rv)?rv:null,updatedAt:getNow()};writePair(k,obj)}catch(e){}}
function startAutoSave(){if(S.saveTimer)clearInterval(S.saveTimer);S.saveTimer=setInterval(saveNow,10000)}
function maybePrompt(){if(S.prompted||!bothReady())return;const k=getPairKey();if(!k)return;prune();const rec=readPair(k);if(!rec)return;const age=getNow()-rec.updatedAt;if(age>TTL)return;S.prompted=true;showResumePrompt(rec)}
function msToTime(s){s=Math.floor(s);const m=Math.floor(s/60);const ss=String(s%60).padStart(2,'0');return m+':'+ss}
function showResumePrompt(rec){const o=document.createElement('div');o.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,0.55);z-index:10000;display:flex;align-items:center;justify-content:center;';const c=document.createElement('div');c.style.cssText='background:rgba(20,20,28,0.95);color:#fff;border:1px solid rgba(255,255,255,0.15);border-radius:8px;min-width:260px;max-width:90vw;padding:14px;font-size:13px;box-shadow:0 10px 30px rgba(0,0,0,0.6);';const t=document.createElement('div');t.textContent='Resume where you left off?';t.style.cssText='font-weight:600;margin-bottom:8px;';const p=document.createElement('div');p.textContent='Last time at '+msToTime(rec.baseTime)+' with delay '+(rec.delay>=0?'+':'')+rec.delay.toFixed(1)+'s';p.style.cssText='opacity:0.9;margin-bottom:12px;';const b=document.createElement('div');b.style.cssText='display:flex;gap:8px;justify-content:flex-end;';const resume=document.createElement('button');resume.textContent='Resume';resume.style.cssText='background:#2e7d32;color:#fff;border:1px solid rgba(255,255,255,0.2);padding:6px 10px;border-radius:6px;';const reset=document.createElement('button');reset.textContent='Start New';reset.style.cssText='background:rgba(255,255,255,0.1);color:#fff;border:1px solid rgba(255,255,255,0.2);padding:6px 10px;border-radius:6px;';b.appendChild(reset);b.appendChild(resume);c.appendChild(t);c.appendChild(p);c.appendChild(b);o.appendChild(c);document.body.appendChild(o);resume.addEventListener('click',function(){try{try{window.isSeeking=true;if(window.markSeeking)window.markSeeking('resume')}catch(e){}if(typeof window.setDelay==='function')window.setDelay(rec.delay);if(rec.pos){const c=document.getElementById('videoReactContainer');if(c){c.style.left=rec.pos.l+'px';c.style.top=rec.pos.t+'px';if(rec.pos.w)c.style.width=rec.pos.w+'px';if(rec.pos.h)c.style.height=rec.pos.h+'px';}}
if(rec.baseVol!=null){try{$('#baseVolumeSlider').val(rec.baseVol);if(window.isBaseYoutubeVideo&&window.baseYoutubePlayer&&window.baseYoutubePlayer.setVolume)window.baseYoutubePlayer.setVolume(rec.baseVol*100);else if($('#videoBaseLocal')[0])$('#videoBaseLocal')[0].volume=rec.baseVol}catch(e){}}
if(rec.reactVol!=null){try{$('#reactVolumeSlider').val(rec.reactVol);if(window.isReactYoutubeVideo&&window.reactYoutubePlayer&&window.reactYoutubePlayer.setVolume)window.reactYoutubePlayer.setVolume(rec.reactVol*100);else if($('#videoReact')[0])$('#videoReact')[0].volume=rec.reactVol}catch(e){}}
setTimeout(function(){try{if(typeof window.syncSeek==='function')window.syncSeek(true,rec.baseTime)}catch(e){}},100);setTimeout(function(){try{if(window.isBaseYoutubeVideo&&window.baseYoutubePlayer&&window.baseYoutubePlayer.playVideo){window.baseYoutubePlayer.playVideo();setTimeout(function(){try{if(window.baseYoutubePlayer.pauseVideo)window.baseYoutubePlayer.pauseVideo();if(window.seekBase)window.seekBase(rec.baseTime,true)}catch(e){}},140)}if(window.isReactYoutubeVideo&&window.reactYoutubePlayer&&window.reactYoutubePlayer.playVideo){const rt=Math.max(0,rec.baseTime+rec.delay);window.reactYoutubePlayer.playVideo();setTimeout(function(){try{if(window.reactYoutubePlayer.pauseVideo)window.reactYoutubePlayer.pauseVideo();if(window.seekReact)window.seekReact(rt,true)}catch(e){}},140)}}catch(e){}},260);setTimeout(function(){try{window.isSeeking=false;if(window.clearSeekingAfterDelay)window.clearSeekingAfterDelay()}catch(e){}},600)}catch(e){}document.body.removeChild(o)});reset.addEventListener('click',function(){try{const k=getPairKey();if(k)localStorage.removeItem(k)}catch(e){}document.body.removeChild(o)});}
function loadLastPair(){const idx=readIndex();if(!idx||!idx.length)return;const rec=readPair(idx.sort((a,b)=>b.t-a.t)[0].k);if(!rec)return;try{window.isSeeking=true;if(window.markSeeking)window.markSeeking('resume')}catch(e){}const applyBase=function(){if(!rec.baseMeta)return; if(rec.baseMeta.type==='yt'&&rec.baseMeta.id){try{$('#videoBaseLocal').hide();$('#videoBaseYoutube').show();$('#videoBaseYoutube').css({width:'100%',height:'100%',display:'block'}); if(window.initializeYouTubePlayer)window.initializeYouTubePlayer(rec.baseMeta.id,false); if(window.Progress&&Progress.recordNetworkSource)Progress.recordNetworkSource('#videoBaseLocal',{type:'yt',id:rec.baseMeta.id}); if(window.updateYouTubePlayers) setTimeout(function(){try{window.updateYouTubePlayers()}catch(e){}},500);}catch(e){}} else if(rec.baseMeta.type==='url'&&rec.baseMeta.url){try{$('#videoBaseYoutube').hide();$('#videoBaseLocal').show();$('#videoBaseLocal').attr('src',rec.baseMeta.url);$('#videoBaseLocal')[0].load(); if(window.Progress&&Progress.recordNetworkSource)Progress.recordNetworkSource('#videoBaseLocal',{url:rec.baseMeta.url});}catch(e){}} else if(rec.baseMeta.type==='file'){try{if(window.selectVideo)window.selectVideo('#videoBaseLocal',null,false)}catch(e){}}};
const applyReact=function(){if(!rec.reactMeta)return; if(rec.reactMeta.type==='yt'&&rec.reactMeta.id){try{$('#videoReact').hide();$('#videoReactYoutube').css({width:'100%',height:'100%',display:'block'}); if(window.initializeYouTubePlayer)window.initializeYouTubePlayer(rec.reactMeta.id,true); if(window.Progress&&Progress.recordNetworkSource)Progress.recordNetworkSource('#videoReact',{type:'yt',id:rec.reactMeta.id}); if(window.updateYouTubePlayers) setTimeout(function(){try{window.updateYouTubePlayers()}catch(e){}},500);}catch(e){}} else if(rec.reactMeta.type==='url'&&rec.reactMeta.url){try{$('#videoReactYoutube').hide();$('#videoReact').show();$('#videoReact').attr('src',rec.reactMeta.url);$('#videoReact')[0].load(); if(window.Progress&&Progress.recordNetworkSource)Progress.recordNetworkSource('#videoReact',{url:rec.reactMeta.url});}catch(e){}} else if(rec.reactMeta.type==='file'){try{if(window.selectVideo)window.selectVideo('#videoReact',null,false)}catch(e){}}};
function once(el,ev,ms){return new Promise(r=>{let t=null;const h=()=>{if(t)clearTimeout(t);el.removeEventListener(ev,h);r()};el.addEventListener(ev,h,{once:true});if(ms)t=setTimeout(()=>{try{el.removeEventListener(ev,h)}catch(e){}r()},ms)})}
function waitYT(){return new Promise(r=>{if(window.YT&&YT.Player)r();else window.addEventListener('youtube-api-ready',()=>r(),{once:true})})}
function loadBase(){if(!rec.baseMeta)return Promise.resolve();const baseT=rec.baseTime; if(rec.baseMeta.type==='yt'&&rec.baseMeta.id){return waitYT().then(()=>{try{$('#videoBaseLocal').hide();$('#videoBaseYoutube').show();$('#videoBaseYoutube').css({width:'100%',height:'100%',display:'block'});if(window.initializeYouTubePlayer)window.initializeYouTubePlayer(rec.baseMeta.id,false)}catch(e){}return new Promise(res=>{let tries=0;const iv=setInterval(()=>{tries++;const p=window.baseYoutubePlayer;const ready=p&&typeof p.getDuration==='function'&&p.getDuration()>0; if(ready||tries>60){clearInterval(iv); try{ if(window.pauseBase) window.pauseBase(true); if(window.seekBase) window.seekBase(baseT,true); setTimeout(()=>{try{ if(window.seekBase) window.seekBase(baseT,true);}catch(e){}},200); setTimeout(()=>{try{ if(window.isBaseYoutubeVideo&&window.baseYoutubePlayer&&window.baseYoutubePlayer.playVideo){window.baseYoutubePlayer.playVideo();setTimeout(()=>{try{if(window.baseYoutubePlayer.pauseVideo)window.baseYoutubePlayer.pauseVideo();if(window.seekBase)window.seekBase(baseT,true)}catch(e){}},140)}}catch(e){}},260);}catch(e){} res()}},100)})})}
if(rec.baseMeta.type==='url'&&rec.baseMeta.url){try{$('#videoBaseYoutube').hide();$('#videoBaseLocal').show();$('#videoBaseLocal').attr('src',rec.baseMeta.url);$('#videoBaseLocal')[0].load()}catch(e){}return once($('#videoBaseLocal')[0],'canplay',5000).then(()=>{try{ if(window.pauseBase) window.pauseBase(true); if(window.seekBase) window.seekBase(baseT,true);}catch(e){}})}
if(rec.baseMeta.type==='file'){if(window.selectVideo)window.selectVideo('#videoBaseLocal',null,false);return once($('#videoBaseLocal')[0],'canplay',10000).then(()=>{try{ if(window.pauseBase) window.pauseBase(true); if(window.seekBase) window.seekBase(baseT,true);}catch(e){}})}
return Promise.resolve()}
function loadReact(){if(!rec.reactMeta)return Promise.resolve();const reactT=Math.max(0, rec.baseTime + rec.delay); if(rec.reactMeta.type==='yt'&&rec.reactMeta.id){return waitYT().then(()=>{try{$('#videoReact').hide();$('#videoReactYoutube').css({width:'100%',height:'100%',display:'block'});if(window.initializeYouTubePlayer)window.initializeYouTubePlayer(rec.reactMeta.id,true)}catch(e){}return new Promise(res=>{let tries=0;const iv=setInterval(()=>{tries++;const p=window.reactYoutubePlayer;const ready=p&&typeof p.getDuration==='function'&&p.getDuration()>0; if(ready||tries>60){clearInterval(iv); try{ if(window.pauseReact) window.pauseReact(true); if(window.seekReact) window.seekReact(reactT,true); setTimeout(()=>{try{ if(window.seekReact) window.seekReact(reactT,true);}catch(e){}},200); setTimeout(()=>{try{ if(window.isReactYoutubeVideo&&window.reactYoutubePlayer&&window.reactYoutubePlayer.playVideo){window.reactYoutubePlayer.playVideo();setTimeout(()=>{try{if(window.reactYoutubePlayer.pauseVideo)window.reactYoutubePlayer.pauseVideo();if(window.seekReact)window.seekReact(reactT,true)}catch(e){}},140)}}catch(e){}},260);}catch(e){} res()}},100)})})}
if(rec.reactMeta.type==='url'&&rec.reactMeta.url){try{$('#videoReactYoutube').hide();$('#videoReact').show();$('#videoReact').attr('src',rec.reactMeta.url);$('#videoReact')[0].load()}catch(e){}return once($('#videoReact')[0],'canplay',5000).then(()=>{try{ if(window.pauseReact) window.pauseReact(true); if(window.seekReact) window.seekReact(reactT,true);}catch(e){}})}
if(rec.reactMeta.type==='file'){if(window.selectVideo)window.selectVideo('#videoReact',null,false);return once($('#videoReact')[0],'canplay',10000).then(()=>{try{ if(window.pauseReact) window.pauseReact(true); if(window.seekReact) window.seekReact(reactT,true);}catch(e){}})}
return Promise.resolve()}
Promise.all([loadBase(),loadReact()]).then(()=>{try{ if(window.updateYouTubePlayers) try{window.updateYouTubePlayers()}catch(e){}; if(typeof window.setDelay==='function') window.setDelay(rec.delay); if(rec.pos){const c=document.getElementById('videoReactContainer');if(c){c.style.left=rec.pos.l+'px';c.style.top=rec.pos.t+'px';if(rec.pos.w)c.style.width=rec.pos.w+'px';if(rec.pos.h)c.style.height=rec.pos.h+'px';}} if(rec.baseVol!=null){try{$('#baseVolumeSlider').val(rec.baseVol);if(window.isBaseYoutubeVideo&&window.baseYoutubePlayer&&window.baseYoutubePlayer.setVolume)window.baseYoutubePlayer.setVolume(rec.baseVol*100);else if($('#videoBaseLocal')[0])$('#videoBaseLocal')[0].volume=rec.baseVol}catch(e){}} if(rec.reactVol!=null){try{$('#reactVolumeSlider').val(rec.reactVol);if(window.isReactYoutubeVideo&&window.reactYoutubePlayer&&window.reactYoutubePlayer.setVolume)window.reactYoutubePlayer.setVolume(rec.reactVol*100);else if($('#videoReact')[0])$('#videoReact')[0].volume=rec.reactVol}catch(e){}} setTimeout(function(){try{ if(window.trySyncVideos) window.trySyncVideos(); if(window.syncVideos) window.syncVideos(true); if(window.updateUIElements) window.updateUIElements(); }catch(e){}},300); setTimeout(function(){try{window.isSeeking=false;if(window.clearSeekingAfterDelay)window.clearSeekingAfterDelay()}catch(e){}},700) }catch(e){}})}
document.addEventListener('visibilitychange',function(){if(document.hidden)saveNow()});
window.addEventListener('beforeunload',function(){saveNow()});
try{prune()}catch(e){}
window.Progress={recordLocalFile,recordNetworkSource,saveNow,loadLastPair}

